- name: Adicionando repositório Helm
  shell: helm repo add stable {{ url_repo_helm }}

- name: Atualizando o repositório Helm
  shell: helm repo update

- name: Instalando o Prometheus Operator
  shell: helm install {{ deploy_prometheus }}