- hosts: local
  gather_facts: no
  roles:
  - role: provisioning
    tags: provisioning

- hosts: k8s_master,k8s_workers
  become: yes
  user: ubuntu
  pre_tasks:
  - name: Atualizando repositório e instalando o Python
    raw: apt update && apt install -y python
  roles:
  - role: install-k8s
    tags: install-k8s

- hosts: k8s_master
  become: yes
  user: ubuntu
  roles:
  - role: create-cluster
    tags: create-cluster

- hosts: k8s_master,k8s_workers
  become: yes
  user: ubuntu
  roles:
  - role: join-workers
    tags: join-workers

- hosts: k8s_master
  become: yes
  user: ubuntu
  roles:
  - role: install-helm
    tags: install-helm

- hosts: k8s_master
  become: yes
  user: ubuntu
  roles:
  - role: deploy-app
    tags: deploy-app